"""
schemas/knowledge_graph.py — PydanticAI schemas for knowledge graph operations.

KGWriteResult is the output contract for Agent 5 (KGWriterAgent).
Entity and Relationship types mirror the Neo4j node/edge labels used in graph_store.py.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class EntityType(str, Enum):
    PARTY = "Party"
    OBLIGATION = "Obligation"
    CONTRACT = "Contract"
    CLAUSE = "Clause"
    REGULATION = "Regulation"


class PartyType(str, Enum):
    VENDOR = "vendor"
    CLIENT = "client"
    COUNTERPARTY = "counterparty"
    UNKNOWN = "unknown"


class Entity(BaseModel):
    """A node to be written to Neo4j."""

    entity_id: str
    entity_type: EntityType
    tenant_id: str
    properties: dict[str, Any] = Field(
        ...,
        description="Key-value properties for this node. Must include tenant_id.",
    )


class Relationship(BaseModel):
    """An edge to be written to Neo4j."""

    from_entity_id: str
    from_entity_type: EntityType
    relationship_type: str = Field(
        ...,
        description="Neo4j relationship label (e.g., PARTY_TO, CONTAINS, CREATES).",
    )
    to_entity_id: str
    to_entity_type: EntityType
    properties: dict[str, Any] = Field(default_factory=dict)


class KGWriteResult(BaseModel):
    """Output schema for Agent 5: KG Writer Agent."""

    contract_id: str
    tenant_id: str
    entities_written: int
    relationships_written: int
    entities: list[Entity]
    relationships: list[Relationship]
    write_errors: list[str] = Field(
        default_factory=list,
        description="Non-fatal write errors (e.g., duplicate node — idempotent merge used).",
    )


class RegulatoryAlert(BaseModel):
    """An alert generated by Agent 7 when a regulatory change impacts a contract."""

    alert_id: str
    tenant_id: str
    contract_id: str
    regulation_id: str
    regulation_title: str
    impact_level: str  # maps to RiskLevel
    changed_section_summary: str
    suggested_action: str
    detected_at: str  # ISO 8601
    n8n_webhook_fired: bool = False
