"""
schemas/knowledge_graph.py — PydanticAI schemas for knowledge graph operations.

KGWriteResult is the output contract for Agent 5 (KGWriterAgent).
Entity and Relationship types mirror the Neo4j node/edge labels used in graph_store.py.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

class GraphEntity(BaseModel):
    """A node to be written to Neo4j."""

    entity_id: str
    entity_type: Literal["party", "obligation", "date", "counterparty", "clause_reference"]
    name: str
    contract_id: str


class GraphRelationship(BaseModel):
    """An edge to be written to Neo4j."""

    from_entity_id: str
    to_entity_id: str
    relationship_type: str = Field(
        ...,
        description="Neo4j relationship label (e.g., obligated_by, references, expires_on)",
    )
    contract_id: str

class KGWriteResult(BaseModel):
    """Output schema for Agent 5: KG Writer Agent."""

    contract_id: str
    tenant_id: str
    entities_written: int
    relationships_written: int
    entities: list[GraphEntity]
    relationships: list[GraphRelationship]
    write_errors: list[str] = Field(
        default_factory=list,
        description="Non-fatal write errors (e.g., duplicate node — idempotent merge used).",
    )


class RegulatoryAlert(BaseModel):
    """An alert generated by Agent 7 when a regulatory change impacts a contract."""

    alert_id: str
    tenant_id: str
    contract_id: str
    regulation_id: str
    regulation_title: str
    impact_level: str  # maps to RiskLevel
    changed_section_summary: str
    suggested_action: str
    detected_at: str  # ISO 8601
    n8n_webhook_fired: bool = False
